@startuml ClassDiagram

namespace Noons{

    namespace NoonEngine{
        

        namespace NoonEngineCore{
            namespace View{
                abstract ADefineView
                abstract AWindowBase

                namespace Objects{
                    class ShaderBase
                }
            }
        }

        namespace GameCore{
            abstract AGameObjectbase
        }
    }

    namespace NoonMath{

        class Matrix
    }

    namespace NoonFileIO{
        class ModelLoader
    }
}

namespace OpenGL{
    class glShader
    class Object
    class Shape

}



@enduml