@startuml PackageDia

package GraphicsBaseLayer{
    package OpenGL
    package DirectX
    package Vulkan
}

package NoonEngine{
    package View
    package GameObject
    package InputManager
}

package JointLayer{
    package 3DDrawer
    package Input 
    package UI
}

package OSOriginal{
    package Win
    package OSX
}

package EX{
    package ImGui
}

NoonEngine <-- JointLayer 
JointLayer <-- GraphicsBaseLayer
JointLayer <-- OSOriginal

UI <- ImGui

View <- 3DDrawer
View <- UI

InputManager <- Input

@enduml